apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ya4jvmhpj-nodejs 
  janus-idp.io/tekton: ya4jvmhpj-nodejs
  backstage.io/kubernetes-id: ya4jvmhpj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ya4jvmhpj-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml